img = iread('SampleData\M623148 (V3).jpg');
%redBinary = binaryImageGenerator(img,'red');
%blueBinary = binaryImageGenerator(img,'blue');
%greenBinary = binaryImageGenerator(img,'green');
%idisp({blueBinary,redBinary,greenBinary,img});
 grey = imono(img);
BW_Sobel = edge(grey,'Sobel');
BW_canny = edge(grey,'Canny');
BW_Prewitt = edge(grey,'Prewitt');
BW_Roberts = edge(grey,'Roberts');
BW_log = edge(grey,'log');
BW_approxcanny = edge(grey,'approxcanny');
%idisp({img,grey});
%idisp({img,grey,BW_Sobel,BW_canny,BW_Prewitt,BW_Roberts,BW_log,BW_approxcanny});
%figure, imshow(BW_approxcanny);
%blobs_all = iblobs(BW_canny,'boundary');
%goodBlobs = blobNoiseReduction(blobs_all);
%idisp({BW_canny,img});
%goodBlobs.plot_box;
centers = imfindcircles(BW_canny,[70 100]);
